version: "3.7" # specify docker-compose version

# Define the services/containers to be run
services:
  frontend: # name of Angular app service
    image: nicolasmura/family-calendar-v2-frontend-public
    container_name: frontend-public
    env_file:
      - .env
    ports:
      - ${HOST_HTTPS_PORT}:443
    volumes:
      - ${ENV_JS}:/usr/local/apache2/htdocs/family-calendar/frontend-public/env.js
      - ${APACHE_LOG}:/var/log/apache2
      - ${SSL_VOLUME}:/var/imported/ssl
    # depends_on:
    #   - database
    #   - backend
    networks:
      family-calendar-v2-network:

  api: # name of Node JS app
    image: nicolasmura/family-calendar-v2-backend-api
    container_name: backend-api
    env_file:
      - .env
    ports:
      - ${NODE_PORT}:${NODE_PORT} # specify ports forwarding
    volumes:
      - .env:/usr/family-calendar-v2/backend-api/.env
    # depends_on:
    #   database:
    #     condition: service_healthy
    restart: on-failure
    networks:
      family-calendar-v2-network:
        aliases:
          - database

networks:
  family-calendar-v2-network:
    driver: bridge
    name: family-calendar-v2-network

# volumes: set in docker-compose.macosx-override.yml & docker-compose.production.yml
