version: "3.7" # specify docker-compose version

# Define the services/containers to be run
services:
  frontend: # name of Angular app service
    image: nicolasmura/family-calendar-v2-frontend-public
    container_name: frontend-v2
    env_file:
      - .env
    ports:
      - ${HOST_HTTPS_PORT}:443
    volumes:
      - ${ENV_JS}:/usr/local/apache2/htdocs/family-calendar/frontend-public/env.js
      - ${APACHE_LOG}:/var/log/apache2
      - ${SSL_VOLUME}:/var/imported/ssl
    depends_on:
      - database
      - api
    networks:
      family-calendar-v2-network:

  api: # name of Node JS app
    image: nicolasmura/family-calendar-v2-backend-api
    # image: test
    container_name: backend-v2
    env_file:
      - .env
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    volumes:
      - .env:/usr/family-calendar-v2/backend-api/dist/apps/backend-api/.env
    depends_on:
      database:
        condition: service_healthy
    restart: on-failure
    networks:
      family-calendar-v2-network:
        aliases:
          - database

  database: # name of database service
    image: nicolasmura/family-calendar-v2-database
    container_name: database-v2
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    command: ["--port", "$DB_PORT", "--logpath", "/var/log/mongodb/mongod.log"] # override the default command to start the service in the container
    healthcheck:
      test: ["CMD", "database-healthcheck.sh"]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 20s
    networks:
      family-calendar-v2-network:
        aliases:
          - database

networks:
  family-calendar-v2-network:
    driver: bridge
    name: family-calendar-v2-network

# volumes: set in docker-compose.macosx-override.yml & docker-compose.production.yml
