// Angular build information, automatically generated by `generate-build-infos` script
export const buildInfo = {
  hash: '<hash>',
  user: '<user>',
  jenkinsBuildId: 123,
  timestamp: '<timestamp>'
};
